services:
  web-morosot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-morosot
    ports:
      - "8390:8080"
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
